### ISSUE TITLE
Unable to use with Yii2 framework...

### ISSUE THREAD

**Issue by davidjeddy** [tiger-seo/PhpBuiltinServer#22]
Config:

``` YAML
extensions:
    enabled:
        - Codeception\Extension\PhpBuiltinServer
    config:
        Codeception\Extension\PhpBuiltinServer:
            hostname: localhost
            port: 8080
            documentRoot: ../../../../
            startDelay: 1
            phpIni: /etc/php.ini
```

Error:

``` HTML
[Tue Nov 17 21:18:50 2015] ::1:49193 [404]: /index-test.php/user/auth/login - No such file or directory
[Tue Nov 17 21:18:51 2015] ::1:49194 [404]: /index-test.php/user/auth/login - No such file or directory
[Tue Nov 17 21:18:51 2015] ::1:49195 [404]: /index-test.php/user/auth/login - No such file or directory
[Tue Nov 17 21:18:51 2015] ::1:49196 [404]: /index-test.php/user/auth/login - No such file or directory
```

Output:

``` CLI
localhost yii2testapp.dev]$ codecept build -c ./protected/yii2testapp/tests/ && codecept run acceptance aProfileBuilderModuleCest -c ./protected/yii2testapp/tests/ --coverage --coverage-xml --coverage-html
Building Actor classes for suites: acceptance, functional, unit
 -> AcceptanceTesterActions.php generated successfully. 0 methods added
\AcceptanceTester includes modules: PhpBrowser, Db
 -> FunctionalTesterActions.php generated successfully. 0 methods added
\FunctionalTester includes modules: Filesystem, Yii2, Db
 -> UnitTesterActions.php generated successfully. 0 methods added
\UnitTester includes modules: Asserts, Db, Yii2
Codeception PHP Testing Framework v2.1.4
Powered by PHPUnit 4.8.18 by Sebastian Bergmann and contributors.

Acceptance Tests (4) -----------------------------------------------------------------------------------------------------------------------------------------
Enable module (aProfileBuilderModuleCest::enableModule)                                                                                                 Fail
Initial population (aProfileBuilderModuleCest::initialPopulation)                                                                                       Fail
Add requirements (aProfileBuilderModuleCest::addRequirements)                                                                                           Fail
Check invalid form (aProfileBuilderModuleCest::checkInvalidForm)                                                                                        Fail
--------------------------------------------------------------------------------------------------------------------------------------------------------------
...
etc
```
