### ISSUE TITLE
Config property is empty using Codeception 2

### ISSUE THREAD

**Issue by grantlucas** [tiger-seo/PhpBuiltinServer#7]
I'm trying to get this up and running on Codeception 2.X and it seems that `$this->config` is empty despite the needed configuration being in `codeception.yml`
## My extension config section

```
extensions:
    enabled:
        - Codeception\Platform\PhpBuiltinServer
    config:
        Codeception\Platform\PhpBuiltinServer:
            hostname: localhost
            port: 9999
            documentRoot: ../../public
            startDelay: 1
```

It doesn't seem that the extension's configuration is being passed in.
